almondiz/almondiz-server

src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/CNotificationNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/CNotificationNotPermittedException.java
src/main/java/org/almondiz/almondiz/notification/Notification.java
src/main/java/org/almondiz/almondiz/notification/NotificationController.java
src/main/java/org/almondiz/almondiz/notification/NotificationRepository.java
src/main/java/org/almondiz/almondiz/notification/NotificationResponseDto.java
src/main/java/org/almondiz/almondiz/notification/NotificationService.java
src/main/java/org/almondiz/almondiz/notification/NotificationType.java
src/main/java/org/almondiz/almondiz/user/UserService.java

Notification 
User 단 상관없이 코드 작성할 수 있을 거라 생각이 들어서 알림 먼저 구현했습니다(사실 필요했지만.. ) 
Notification 구현 
- 메세지 타입을 enum으로 생성해봤고, 자세한 텍스트는 정해야 할 것 같아요 
- 아직 토큰 쪽 코드를 안 넣어놔서 임시로 아래처럼 해놨습니다. 토큰 로직을 넣게 되면 토큰 안에 이메일 정보가 있어서 아래 주석처럼 그 이메일로 사용자를 찾을 수 있어요(토큰만으로 사용자 식별이 가능합니다)
##
그래서 의논 드리고 싶은 부분이 api url안에 userId가 안 쓰이기도 하고, 쓰인다면 보안적으로 고민이 되어서 .. 이 부분에 대해서 논의가 필요하다고 생각이 듭니다..! 
closes #16

Feature/#16 Notification 

---

src/main/java/org/almondiz/almondiz/common/TimeStamped.java
src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/CFollowExistedException.java
src/main/java/org/almondiz/almondiz/exception/exception/CFollowNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/CFollowNotPermittedException.java
src/main/java/org/almondiz/almondiz/follow/Follow.java
src/main/java/org/almondiz/almondiz/follow/FollowController.java
src/main/java/org/almondiz/almondiz/follow/FollowRepository.java
src/main/java/org/almondiz/almondiz/follow/FollowRequestDto.java
src/main/java/org/almondiz/almondiz/follow/FollowService.java
src/main/java/org/almondiz/almondiz/follow/FollowerResponseDto.java
src/main/java/org/almondiz/almondiz/follow/FollowingResponseDto.java
src/main/java/org/almondiz/almondiz/user/UserService.java

Follow 구현 
내용을 적어주세요.
UserService 변경이 있어서 이슈 16(이랑 겹치는 부분 있음) 머지하면 아마 conflict가 날 수도 있을 것 같아요 
closes #15

Feature/#15 Follow 구현 

---

src/main/java/org/almondiz/almondiz/user/UserService.java

UserService 중복 메소드 수정 
UserService 중복 메소드 수정 
getUserByEmail이 중복이었습니다
closes #27

[bugfix] #27 UserService 중복 메소드 수정 

---

src/main/java/org/almondiz/almondiz/category/entity/Category.java
src/main/java/org/almondiz/almondiz/config/security/SecurityConfig.java
src/main/java/org/almondiz/almondiz/exception/exception/PostFileNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/PostNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/StoreNotFoundException.java
src/main/java/org/almondiz/almondiz/follow/FollowService.java
src/main/java/org/almondiz/almondiz/nut/NutService.java
src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/post/dto/PostRequestDto.java
src/main/java/org/almondiz/almondiz/post/dto/PostResponseDto.java
src/main/java/org/almondiz/almondiz/post/entity/Post.java
src/main/java/org/almondiz/almondiz/post/entity/PostRepository.java
src/main/java/org/almondiz/almondiz/postFile/PostFileService.java
src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
src/main/java/org/almondiz/almondiz/postFile/entity/PostFileRepository.java
src/main/java/org/almondiz/almondiz/profileFile/ProfileFileService.java
src/main/java/org/almondiz/almondiz/store/StoreService.java
src/main/java/org/almondiz/almondiz/store/entity/Store.java
src/main/java/org/almondiz/almondiz/store/entity/StoreRepository.java
src/main/java/org/almondiz/almondiz/store/entity/StoreService.java
src/main/java/org/almondiz/almondiz/tag/TagService.java
src/main/java/org/almondiz/almondiz/user/UserController.java
src/main/java/org/almondiz/almondiz/user/UserService.java
src/main/java/org/almondiz/almondiz/user/entity/User.java

글쓰기(Post) 구현
- 리뷰 작성 
- 모든 리뷰 조회 
- 리뷰 단건 조회 
- 사용자별 리뷰 조회 
- 상점별 리뷰 조회 
- 리뷰 삭제 
- 리뷰 수정 
- 위치별 post 조회는 거리 기준이 명확하지 않아서 구현을 미뤘습니다. 
- entity 안에 있는 FK를 객체로 모두 바꿨습니다. (변경하는 과정에서 약간 스파게티가 된 듯 한데... 나중에 리팩토링 과정을 해야할것 같아요 ㅜㅜ)
- 구현한 api는 Swagger 테스트 모두 마쳤습니다. 
- 기존 논의 사항은 별도의 Issue 로 등록하였습니다. 
closes #17

Feature/#17 글쓰기(Post) 구현

---

build.gradle
src/main/java/org/almondiz/almondiz/comment/CommentController.java
src/main/java/org/almondiz/almondiz/common/ValidStringUtils.java
src/main/java/org/almondiz/almondiz/config/security/CAccessDeniedHandler.java
src/main/java/org/almondiz/almondiz/config/security/CAuthenticationEntryPoint.java
src/main/java/org/almondiz/almondiz/config/security/ExceptionController.java
src/main/java/org/almondiz/almondiz/config/security/JwtAuthenticationFilter.java
src/main/java/org/almondiz/almondiz/config/security/SecurityConfig.java
src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/CAccessDeniedException.java
src/main/java/org/almondiz/almondiz/exception/exception/CAuthenticationEntryPointException.java
src/main/java/org/almondiz/almondiz/exception/exception/CExpiredTokenException.java
src/main/java/org/almondiz/almondiz/exception/exception/CNotValidEmailException.java
src/main/java/org/almondiz/almondiz/exception/exception/CRefreshTokenException.java
src/main/java/org/almondiz/almondiz/exception/exception/CTokenUserNotFoundException.java
src/main/java/org/almondiz/almondiz/follow/FollowController.java
src/main/java/org/almondiz/almondiz/notification/NotificationController.java
src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/user/AuthService.java
src/main/java/org/almondiz/almondiz/user/UserController.java
src/main/java/org/almondiz/almondiz/user/UserService.java
src/main/java/org/almondiz/almondiz/user/dto/UserLogInDto.java
src/main/java/org/almondiz/almondiz/user/entity/Token.java
src/main/java/org/almondiz/almondiz/user/entity/User.java

JWT 및 Security 적용하여 AuthService 생성 및 수정, 헤더 추가
JWT 및 시큐리티 설정 - token 발급 및 적용을 위해 AuthService 생성, 회원 관련 로직 변경(UserService 부분포함) 
main 브랜치 기준 Controller에 토큰 헤더 추가, uri 수정  
회원가입 이메일 유효성검사 추가  
closes #12 
closes #25

JWT 및 Security 적용하여 AuthService 생성 및 수정, 헤더 추가

---

src/main/resources/application.properties

DB 서버 세팅
application.properties 파일에 디비 세팅 
배포할 때 application-cloud.properties 에 디비 서버 정보 넣어주면 될 것 같아요

[feature] #31 DB 서버 세팅

---

src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/StoreExistedException.java
src/main/java/org/almondiz/almondiz/store/StoreService.java
src/main/java/org/almondiz/almondiz/store/entity/Store.java
src/main/java/org/almondiz/almondiz/store/entity/StoreRepository.java
src/main/java/org/almondiz/almondiz/store/entity/StoreRequestDto.java
src/main/java/org/almondiz/almondiz/store/entity/StoreResponseDto.java

Store CRUD 로직 구현
API를 통해 식당 엔티티 생성을 위한 로직 구현 
내용을 적어주세요.
closes #42

[feature] #42 Store CRUD 로직 구현

---

src/main/java/org/almondiz/almondiz/config/security/CorsConfig.java
src/main/java/org/almondiz/almondiz/config/security/SecurityConfig.java

cors error
https://velog.io/@minnseong/CORS-with-Spring-MVC-Security
내용을 적어주세요.
개발 서버에 배포 후 테스트 필요 -> 성공 시 이슈 닫을 예정

[bugfix] #45 cors error

---

src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/StoreScrapExistedException.java
src/main/java/org/almondiz/almondiz/exception/exception/StoreScrapNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/StoreScrapNotPermittedException.java
src/main/java/org/almondiz/almondiz/nut/NutService.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/postFile/PostFileService.java
src/main/java/org/almondiz/almondiz/profileFile/ProfileFileService.java
src/main/java/org/almondiz/almondiz/store/StoreService.java
src/main/java/org/almondiz/almondiz/storescrap/StoreScrap.java
src/main/java/org/almondiz/almondiz/storescrap/StoreScrapController.java
src/main/java/org/almondiz/almondiz/storescrap/StoreScrapRepository.java
src/main/java/org/almondiz/almondiz/storescrap/StoreScrapResponseDto.java
src/main/java/org/almondiz/almondiz/storescrap/StoreScrapService.java
src/main/java/org/almondiz/almondiz/tag/TagService.java
src/main/java/org/almondiz/almondiz/user/UserService.java

StoreScrap 
추가된 api가 있는데 (문서에 없는) 설계해봤습니다. 혹시 피드백 있으시면 편하게 코멘트로 주세여~!
Service에 @Setter 어노테이션  필요없을 것 같아서 뺐습니다! 
closes #43

Feature/#43 StoreScrap 

---

src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/comment/dto/CommentResponseDto.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/post/dto/PostResponseDto.java
src/main/java/org/almondiz/almondiz/post/entity/Post.java
src/main/java/org/almondiz/almondiz/user/UserService.java
src/main/java/org/almondiz/almondiz/user/dto/UserAsWriterResponseDto.java
src/main/resources/application-cloud.properties

post 디테일 페이지 api 구현
기존 PostResponseDto의 데이터들을 프론트엔드 쪽에서 보기 편하게 정돈하였습니다! 
내용을 적어주세요.

[feature] #49 post 디테일 페이지 api 구현

---

src/main/java/org/almondiz/almondiz/comment/entity/CommentRepository.java
src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/post/dto/PostInFeedResponseDto.java

피드 API 구현 
가장 최근 댓글 하나만 보여주는 피드용 Dto를 만들었습니다. (PostInFeedResponseDto) 
JPA로 where 절과 limit 절을 함께 하는 방법이 무엇일까요..? 
- limit 절만 사용하는 방법 
findFirstByOrderByCreatedAtDesc()
- where 절만 사용하는 방법 
findByPost(post)
여기까지는 잘 동작하는데 아래처럼 where & limit 함께 사용하니 에러가 발생하네요.. 
findFirstByPostOrderByCreatedAtDesc(post)
혹시 아는 분 계시면 조언 부탁드립니다! 
제가 참고한 자료는 [Spring Data JPA - Limiting Query Results](https://www.logicbig.com/tutorials/spring-framework/spring-data/limiting-query-results.html) 입니다

Feature/#50 피드 API 구현 

---

src/main/java/org/almondiz/almondiz/comment/CommentController.java
src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/common/TimeStamped.java
src/main/java/org/almondiz/almondiz/config/security/SecurityConfig.java
src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/follow/FollowController.java
src/main/java/org/almondiz/almondiz/follow/FollowService.java
src/main/java/org/almondiz/almondiz/notification/NotificationController.java
src/main/java/org/almondiz/almondiz/notification/NotificationService.java
src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/storescrap/StoreScrapController.java
src/main/java/org/almondiz/almondiz/storescrap/StoreScrapService.java
src/main/java/org/almondiz/almondiz/user/AuthService.java
src/main/java/org/almondiz/almondiz/user/UserController.java
src/main/java/org/almondiz/almondiz/user/UserService.java
src/main/java/org/almondiz/almondiz/user/dto/UserLogInDto.java
src/main/java/org/almondiz/almondiz/user/dto/UserRegisterDto.java
src/main/java/org/almondiz/almondiz/user/dto/UserResponseDto.java
src/main/java/org/almondiz/almondiz/user/entity/User.java
src/main/java/org/almondiz/almondiz/user/entity/UserRepository.java

uid 변경
😿 
디비 email null 해제했습니다 
디비 커스텀 나중에 따로 해야겠어요 예를 들어 string 길이?
closes #62 
closes #22

Feature/#62 uid 변경, 서비스 로직에 적용 

---

src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/comment/dto/CommentResponseDto.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/post/dto/PostInFeedResponseDto.java
src/main/java/org/almondiz/almondiz/post/dto/PostResponseDto.java
src/main/java/org/almondiz/almondiz/user/AuthService.java
src/main/java/org/almondiz/almondiz/user/UserController.java
src/main/java/org/almondiz/almondiz/user/UserService.java
src/main/java/org/almondiz/almondiz/user/dto/UserRegisterDto.java
src/main/java/org/almondiz/almondiz/user/dto/UserRequestDto.java
src/main/java/org/almondiz/almondiz/user/dto/UserResponseDto.java
src/main/java/org/almondiz/almondiz/user/dto/UserSimpleResponseDto.java
src/main/java/org/almondiz/almondiz/user/entity/Thumb.java
src/main/java/org/almondiz/almondiz/user/entity/User.java

thumb 추가, user dto 수정
emoji, color 의 thumb 추가, db 변경
user 조회 dto 수정 
profileimg 컬럼 삭제는 우선 일단 보류 
closes #66

[feature] #66 thumb 추가, user dto 수정

---

src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/TagExistedException.java
src/main/java/org/almondiz/almondiz/exception/exception/TagPostNotFoundException.java
src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/post/dto/PostRequestDto.java
src/main/java/org/almondiz/almondiz/post/dto/PostSimpleResponseDto.java
src/main/java/org/almondiz/almondiz/post/entity/Post.java
src/main/java/org/almondiz/almondiz/postFile/PostFileService.java
src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
src/main/java/org/almondiz/almondiz/tag/TagService.java
src/main/java/org/almondiz/almondiz/tag/entity/Tag.java
src/main/java/org/almondiz/almondiz/tag/entity/TagRepository.java
src/main/java/org/almondiz/almondiz/tagpost/TagPostService.java
src/main/java/org/almondiz/almondiz/tagpost/entity/TagPost.java
src/main/java/org/almondiz/almondiz/tagpost/entity/TagPostRepository.java

Post API 수정 
Post API dto 수정
tag, image 등록 기능 추가 
내용을 적어주세요.
closes #61

Feature/#61 Post API 수정 

---

src/main/java/org/almondiz/almondiz/tag/TagController.java
src/main/java/org/almondiz/almondiz/tag/TagService.java
src/main/java/org/almondiz/almondiz/tag/dto/TagRequestDto.java
src/main/java/org/almondiz/almondiz/tag/entity/TagRepository.java

Tag API
Tag API
내용을 적어주세요.
closes #78

Feature/#78 Tag API

---

src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/PostScrapExistedException.java
src/main/java/org/almondiz/almondiz/exception/exception/PostScrapNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/PostScrapNotPermittedException.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/postscrap/PostScrap.java
src/main/java/org/almondiz/almondiz/postscrap/PostScrapController.java
src/main/java/org/almondiz/almondiz/postscrap/PostScrapRepository.java
src/main/java/org/almondiz/almondiz/postscrap/PostScrapResponseDto.java
src/main/java/org/almondiz/almondiz/postscrap/PostScrapService.java

postScrap 구현 
postScrap 구현 
post api dto에 적용 
내용을 적어주세요.
closes #72

Feature/#72 postScrap 구현 

---

src/main/java/org/almondiz/almondiz/post/PostService.java

내용을 적어주세요.
내용을 적어주세요.
내용을 적어주세요.
closes #82

[bugfix] #82 post create uid로 user 조회

---

src/main/java/org/almondiz/almondiz/category/CategoryController.java
src/main/java/org/almondiz/almondiz/category/CategoryService.java
src/main/java/org/almondiz/almondiz/category/entity/CategoryRepository.java

내용을 적어주세요.
내용을 적어주세요.
내용을 적어주세요.
closes #46

[feature] #46 category create api 생성

---

src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/ReportExistedException.java
src/main/java/org/almondiz/almondiz/report/Report.java
src/main/java/org/almondiz/almondiz/report/ReportController.java
src/main/java/org/almondiz/almondiz/report/ReportRepository.java
src/main/java/org/almondiz/almondiz/report/ReportRequestDto.java
src/main/java/org/almondiz/almondiz/report/ReportService.java

Post Report 기능 구현
Post Report 기능 구현
내용을 적어주세요.
closes #73

[feature] #73 Post Report 기능 구현

---

src/main/java/org/almondiz/almondiz/comment/CommentController.java
src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/comment/dto/CommentResponseDto.java
src/main/java/org/almondiz/almondiz/comment/entity/Comment.java
src/main/java/org/almondiz/almondiz/commentlike/CommentLike.java
src/main/java/org/almondiz/almondiz/commentlike/CommentLikeController.java
src/main/java/org/almondiz/almondiz/commentlike/CommentLikeRepository.java
src/main/java/org/almondiz/almondiz/commentlike/CommentLikeService.java
src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/CommentLikeExistedException.java
src/main/java/org/almondiz/almondiz/exception/exception/CommentLikeNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/CommentLikeNotPermittedException.java
src/main/java/org/almondiz/almondiz/follow/FollowController.java
src/main/java/org/almondiz/almondiz/notification/NotificationController.java
src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/postscrap/PostScrapController.java
src/main/java/org/almondiz/almondiz/report/ReportController.java
src/main/java/org/almondiz/almondiz/tag/TagController.java

댓글 좋아요 구현 
댓글 좋아요 구현 
내용을 적어주세요.
closes #87

Feature/#87 댓글 좋아요 구현 

---

src/main/java/org/almondiz/almondiz/comment/CommentController.java
src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/comment/dto/CommentResponseDto.java
src/main/java/org/almondiz/almondiz/commentlike/CommentLikeController.java
src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
src/main/java/org/almondiz/almondiz/exception/exception/ReplyExistedException.java
src/main/java/org/almondiz/almondiz/exception/exception/ReplyLikeExistedException.java
src/main/java/org/almondiz/almondiz/exception/exception/ReplyLikeNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/ReplyNotFoundException.java
src/main/java/org/almondiz/almondiz/exception/exception/ReplyNotPermittedException.java
src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/postscrap/PostScrapController.java
src/main/java/org/almondiz/almondiz/reply/Reply.java
src/main/java/org/almondiz/almondiz/reply/ReplyController.java
src/main/java/org/almondiz/almondiz/reply/ReplyRepository.java
src/main/java/org/almondiz/almondiz/reply/ReplyRequestDto.java
src/main/java/org/almondiz/almondiz/reply/ReplyResponseDto.java
src/main/java/org/almondiz/almondiz/reply/ReplyService.java
src/main/java/org/almondiz/almondiz/replylike/ReplyLike.java
src/main/java/org/almondiz/almondiz/replylike/ReplyLikeController.java
src/main/java/org/almondiz/almondiz/replylike/ReplyLikeRepository.java
src/main/java/org/almondiz/almondiz/replylike/ReplyLikeService.java
src/main/java/org/almondiz/almondiz/report/ReportController.java

대댓글 및 대댓글 좋아요 구현 
대댓글 및 대댓글 좋아요 구현 
내용을 적어주세요.
closes #91 
closes #86 
closes #74

Feature/#86 대댓글 및 대댓글 좋아요 구현 

---

src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/commentlike/CommentLikeService.java
src/main/java/org/almondiz/almondiz/reply/ReplyService.java
src/main/java/org/almondiz/almondiz/replylike/ReplyLikeService.java

like count 수정
like count 수정
내용을 적어주세요.
closese #93

Bugfix/#93 좋아요 개수 수정 

---

src/main/java/org/almondiz/almondiz/user/AuthService.java
src/main/java/org/almondiz/almondiz/user/UserController.java
src/main/java/org/almondiz/almondiz/user/dto/TokenUserIdResponseDto.java

login responseDto에 userId 추가
login responseDto에 userId 추가
내용을 적어주세요.
closes #95

[feature] #95 login responseDto에 userId 추가

---

src/main/java/org/almondiz/almondiz/post/PostController.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/resources/application-cloud.properties

post 관련 버그 수정 
커밋 메세지 확인  
내용을 적어주세요.
closes #97

Bugfix/#97 post 관련 버그 수정 

---

src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/comment/dto/CommentResponseDto.java
src/main/java/org/almondiz/almondiz/common/Relation.java
src/main/java/org/almondiz/almondiz/follow/FollowService.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/post/dto/PostResponseDto.java

relation dto에 추가 
relation을 post, comment dto에 추가 
내용을 적어주세요.

Feature/#99 relation dto에 추가 

---

src/main/java/org/almondiz/almondiz/comment/CommentService.java
src/main/java/org/almondiz/almondiz/post/PostService.java
src/main/java/org/almondiz/almondiz/reply/ReplyController.java
src/main/java/org/almondiz/almondiz/reply/dto/ReplyRequestDto.java
src/main/java/org/almondiz/almondiz/reply/dto/ReplyResponseDto.java
src/main/java/org/almondiz/almondiz/reply/entity/Reply.java
src/main/java/org/almondiz/almondiz/reply/entity/ReplyRepository.java
src/main/java/org/almondiz/almondiz/reply/replylike/ReplyLike.java
src/main/java/org/almondiz/almondiz/reply/replylike/ReplyLikeController.java
src/main/java/org/almondiz/almondiz/reply/replylike/ReplyLikeRepository.java

내용을 적어주세요.
내용을 적어주세요.
내용을 적어주세요.

[feature] #107 대댓글 구현
